### ISSUE TITLE
frame-loop

### ISSUE THREAD

**Issue by mattdesl** [Jam3/tech-we-use#1]
i was using frame-loop for a bit in my tweening stuff, and found it was leading to choppy animations. Looks like it tries to maintain a fixed framerate or something. Going from frame-loop to a simple raf loop gave me a significant FPS boost and got rid of choppiness.

https://www.npmjs.com/package/raf-loop

**Comment by mikkoh** [comment]
Hmmm... I haven't noticed it. Hmmmm... Have to investigate. I think I might be using it for `kimi`

**Comment by mikkoh** [comment]
My bad I'm using raf-loop. Do you want to modify and `remove frame-loop`?

**Comment by mikkoh** [comment]
@mattdesl switched it to be raf-loop
